FROM node:16

WORKDIR /usr/src/app
COPY * /usr/src/app/
RUN npm install -g npm@latest
RUN npm install -g nodemon@latest
RUN npm install
COPY node_modules /usr/src/app/node_modules
CMD [ "npm", "run", "dev" ]
