const levels = [
    {
        id:1,
        label: "A1",
        ref: "A1",
        description :"Utilisateur élémentaire (niveau introductif ou de découverte)",
        test_id: 1,
        isArchive: false,
    },
    {
        id:2,
        label: "A2",
        ref: "A2",
        description :"Utilisateur élémentaire (niveau intermédiaire ou usuel)",
        test_id: 1,
        isArchive: false,
    },
    {
        id:3,
        label: "B1",
        ref: "B1",
        description :"Utilisateur indépendant (niveau seuil)",
        test_id: 1,
        isArchive: false,
    },
    {
        id:4,
        label: "C1",
        ref: "C1",
        description :"Utilisateur expérimenté (niveau autonome)",
        test_id: 1,
        isArchive: false,
    },
    {
        id:5,
        label: "C2",
        ref: "C2",
        description :"Utilisateur expérimenté (niveau maîtrise)",
        test_id: 1,
        isArchive: false,
    },
    {
        id:6,
        label: "N5",
        ref: "JLPT-N5",
        description :"",
        test_id: 3,
        isArchive: false,
    },
    {
        id:7,
        label: "N4",
        ref: "JLPT-N4",
        description :"",
        test_id: 3,
        isArchive: false,
    },
    {
        id:8,
        label: "N3",
        ref: "JLPT-N3",
        description :"",
        test_id: 3,
        isArchive: false,
    },
    {
        id:9,
        label: "N2",
        ref: "JLPT-N2",
        description :"",
        test_id: 3,
        isArchive: false,
    },
    {
        id:10,
        label: "N1",
        ref: "JLPT-N1",
        description :"",
        test_id: 3,
        isArchive: false,
    },
    {
        id:11,
        label: "A1",
        ref: "A1",
        description :"Utilisateur élémentaire (niveau introductif ou de découverte)",
        test_id: 5,
        isArchive: false,
    },
    {
        id:12,
        label: "A2",
        ref: "A2",
        description :"",
        test_id: 5,
        isArchive: false,
    },
    {
        id:13,
        label: "A1",
        ref: "A1",
        description :"",
        test_id: 2,
        isArchive: false,
    },
    {
        id:14,
        label: "A2",
        ref: "A2",
        description :"",
        test_id: 2,
        isArchive: false,
    }
]


module.exports = levels;