const users = [
    {
        user_id: 1,
        login: "bauer",
        password: "bb1212",
        email: "bbauer02@gmail.com",
        phone: '+330323522248',
        gender: 1,
        civility: 1,
        firstname: "Baptiste",
        lastname: "Bauer",
        adress1: "30 rue Robert Leroux",
        adress2: "",
        zipcode: "02000",
        city: "laon",
        country_id: 76,
        birthday: new Date(1982, 7, 4),
        nationality_id: 76,
        firstlanguage_id: 1,
        systemRole_id: 5
    },
    {
        user_id: 2,
        login: "umebosi1014",
        password: "ume1014",
        email: "umebosi1014@yahoo.co.jp",
        phone: '0706050403',
        gender: 2,
        civility: 2,
        firstname: "Ayaka",
        lastname: "Oyama",
        adress1: "3 rue Georges Citerne",
        adress2: "Apt 1",
        zipcode: "75015",
        city: "paris",
        country_id: 76,
        birthday: new Date(1988, 9, 14),
        nationality_id: 112,
        firstlanguage_id: 2,
        systemRole_id: 1
    },
    {
        user_id: 3,
        login: "cLefebre",
        password: "lfvr1234*",
        email: "cLefebre@gmail.com",
        phone: '123456789',
        gender: 1,
        civility: 1,
        firstname: "Christophe",
        lastname: "Lefebre",
        adress1: "5 boulevard Voltaire",
        adress2: "Apt 6",
        zipcode: "13000",
        city: "marseille",
        country_id: 76,
        birthday: new Date(1987, 10, 14),
        nationality_id: 76,
        firstlanguage_id: 3,
        systemRole_id: 1
    },
    {
        user_id: 4,
        login: "didierM",
        password: "Didi--51",
        email: "didierMoulard@gmail.com",
        phone: '1234567899',
        gender: 1,
        civility: 1,
        firstname: "Didier",
        lastname: "Moulard",
        adress1: "2 rue du Louvres",
        zipcode: "51100",
        city: "Reims",
        country_id: 76,
        birthday: new Date(1987, 10, 14),
        nationality_id: 76,
        firstlanguage_id: 3,
        systemRole_id: 1
    }
];
module.exports = users;